# Generated by Django 5.1.4 on 2024-12-18 11:15

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='about_me',
            field=models.TextField(blank=True, null=True, verbose_name='About Me'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region='RU', verbose_name='Phone'),
        ),
        migrations.AddField(
            model_name='user',
            name='tg_contact',
            field=models.URLField(blank=True, max_length=50, null=True, verbose_name='TG'),
        ),
        migrations.AddField(
            model_name='user',
            name='vk_contact',
            field=models.URLField(blank=True, max_length=50, null=True, verbose_name='VK'),
        ),
    ]
